env:
  global:
    - CC_TEST_REPORTER_ID=334c6a6a666d4b4d6b4e5d00a16639ff9da8e649901e95a623706004ae75f935
language: ruby
rvm:
 - 2.5.1
before_install:
- gem update --system
- gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- export RAILS_ENV=test
- bundle exec rake db:drop db:create db:migrate
- bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
