default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pandemic_development
test:
  <<: *default
  database: pandemic_test

production:
  <<: *default
  database: pandemic_production
  username: pandemic
  password: <%= ENV['PANDEMIC_DATABASE_PASSWORD'] %>
